### ISSUE TITLE
Error executing task (java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException)

### ISSUE THREAD

**Issue by L4BORG** [PaperSpigot/Paper-1.7#55]
```
[21:44:28 FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 50, Size: 45
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_60]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_60]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:45) [spigot-acidisland.jar:git-PaperSpigot-25a137f-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:771) [spigot-acidisland.jar:git-PaperSpigot-25a137f-53fac9f]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot-acidisland.jar:git-PaperSpigot-25a137f-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:710) [spigot-acidisland.jar:git-PaperSpigot-25a137f-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:613) [spigot-acidisland.jar:git-PaperSpigot-25a137f-53fac9f]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.IndexOutOfBoundsException: Index: 50, Size: 45
        at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_60]
        at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_60]
        at net.minecraft.server.v1_8_R3.Container.getSlot(Container.java:109) ~[spigot-acidisland.jar:git-PaperSpigot-25a137f-53fac9f]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1466) ~[spigot-acidisland.jar:git-PaperSpigot-25a137f-53fac9f]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) ~[spigot-acidisland.jar:git-PaperSpigot-25a137f-53fac9f]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) ~[spigot-acidisland.jar:git-PaperSpigot-25a137f-53fac9f]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) ~[spigot-acidisland.jar:git-PaperSpigot-25a137f-53fac9f]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_60]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_60]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[spigot-acidisland.jar:git-PaperSpigot-25a137f-53fac9f]
        ... 5 more
```

this just popped out...

```
This server is running CraftBukkit version git-PaperSpigot-25a137f-53fac9f (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
```

**Comment by MelonCode** [comment]
Just got this issue too

**Comment by Zbob750** [comment]
Please provide the crash report, and any logs you have. Even if they appear identical they could help. :)
